### PR TITLE
Add files for report on submission 011

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by nuest** [comment]
@anitagraser Thanks - report looks good! Do you want me to merge this now, or should we leave it open until the report is finalised (i.e, it includes the full citation of the paper) ?

One comment on the summary: With a partial reproduction and mismatching figures, it would be interesting to read your impression about the reason and the overall material, something like this might fit: _"All code could be executed with help from the authors and it seems that the provided data and software is complete."_ What are the differences between the figures: completely different results?

**Comment by anitagraser** [comment]
Thanks Daniel! No need to merge right now. Let's wait until it is finalized. 

I'll also add some more details in the summary, as you suggested.

**Comment by anitagraser** [comment]
https://osf.io/g4dcq/ is public now. We should be good to go.

**Comment by nuest** [comment]
@anitagraser Great!

Please don't forget to mint a DOI for the OSF project. The link from the badge at https://agile-giss.copernicus.org/articles/2/4/2021/ will only resolve then.

**Comment by anitagraser** [comment]
Thanks! OSF DOI should be created now.

**Pull request merged**
